export const icons = [
	'fab fa-angular',
	'fab fa-apple',
	'fas fa-atlas',
	'fas fa-atom',
	'fas fa-bahai',
	'fas fa-biohazard',
	'fab fa-bitcoin',
	'fas fa-bomb',
	'fas fa-blender',
	'fab fa-bluetooth',
	'fas fa-brain',
	'fas fa-chess-rook',
	'fas fa-cogs',
	'fas fa-compass',
	'fab fa-css3-alt',
	'fab fa-docker',
	'fas fa-dove',
	'fas fa-fish',
]
